# Generated by Django 4.2.1 on 2023-07-21 10:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_comment_approved_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
